package main

import "fmt"

func nodesinit() {
	nodes = make(map[string]*node)
	connections = make(map[string]map[string]struct{})
	addNode("Velia", 0)
	addConnection("Velia", "Luivano Island")
	addConnection("Velia", "Finto Farm")
	addConnection("Velia", "Forest of Plunder")
	addConnection("Velia", "Bartali Farm")
	addConnection("Velia", "Loggia Farm")
	addConnection("Velia", "Coastal Cave")
	addNode("Luivano Island", 1)
	addProductionNode("Luivano Island", "A", 1, "Velia", "Dried Skipjack", "Dried Dolphin Fish", "Dried Striped Catfish", "Dried Surfperch")
	addConnection("Luivano Island", "Mariveno Island")
	addConnection("Luivano Island", "Paratama Island")
	// TODO: addConnection("Luivano Island", "Ephde Rune Island")
	addConnection("Luivano Island", "Velia")
	// TODO: addConnection("Luivano Island", "Duch Island")
	addNode("Mariveno Island", 1)
	addProductionNode("Mariveno Island", "A", 1, "Velia", "Dried Striped Catfish", "Dried Bluefish", "Dried Clownfish", "Dried Siganid")
	addProductionNode("Mariveno Island", "B", 1, "Velia", "Dried Striped Catfish", "Dried Filefish", "Dried Skipjack", "Dried Siganid")
	addConnection("Mariveno Island", "Luivano Island")
	addNode("Finto Farm", 2)
	addProductionNode("Finto Farm", "A", 1, "Velia", "Potato")
	addProductionNode("Finto Farm", "B", 1, "Velia", "Chicken Meat", "Egg")
	addConnection("Finto Farm", "Ehwaz Hill")
	addConnection("Finto Farm", "Velia")
	addNode("Forest of Plunder", 1)
	addProductionNode("Forest of Plunder", "A", 1, "Velia", "Arrow Mushroom", "Big Arrow Mushroom")
	addConnection("Forest of Plunder", "Ehwaz Hill")
	addConnection("Forest of Plunder", "Goblin Cave")
	addConnection("Forest of Plunder", "Heidel Pass")
	addConnection("Forest of Plunder", "Velia")
	addNode("Bartali Farm", 2)
	addConnection("Bartali Farm", "Velia")
	addProductionNode("Bartali Farm", "A", 1, "Velia", "Potato")
	addProductionNode("Bartali Farm", "B", 1, "Velia", "Chicken Meat", "Egg")
	addConnection("Bartali Farm", "Balenos Forest")
	addConnection("Bartali Farm", "Marino Farm")
	addConnection("Bartali Farm", "Toscani Farm")
	addNode("Loggia Farm", 2)
	addProductionNode("Loggia Farm", "A", 1, "Velia", "Potato")
	addConnection("Loggia Farm", "Velia")
	addConnection("Loggia Farm", "Imp Cave")
	addNode("Coastal Cave", 1)
	addProductionNode("Coastal Cave", "A", 1, "Velia", "Copper Ore", "Powder of Flame")
	addProductionNode("Coastal Cave", "B", 1, "Velia", "Iron Ore", "Powder of Darkness")
	addConnection("Coastal Cave", "Velia")
	addConnection("Coastal Cave", "Coastal Cliff")
	addNode("Ehwaz Hill", 1)
	addProductionNode("Ehwaz Hill", "A", 1, "Velia", "Fortune Teller Mushroom", "Big Fortune Teller Mushroom")
	addProductionNode("Ehwaz Hill", "B", 1, "Velia", "Ash Timber", "Ash Sap")
	addConnection("Ehwaz Hill", "Forest of Plunder")
	addConnection("Ehwaz Hill", "Finto Farm")
	addConnection("Ehwaz Hill", "Cron Castle Site")
	addNode("Goblin Cave", 2)
	addProductionNode("Goblin Cave", "A", 1, "Velia", "Copper Ore", "Rough Translucent Crystal")
	addProductionNode("Goblin Cave", "B", 1, "Velia", "Ash Timber", "Spirit's Leaf")
	addConnection("Goblin Cave", "Forest of Plunder")
	addNode("Heidel Pass", 3)
	addConnection("Heidel Pass", "Northern Guard Camp")
	addConnection("Heidel Pass", "Balenos Forest")
	addConnection("Heidel Pass", "Forest of Plunder")
	addNode("Balenos Forest", 2)
	addProductionNode("Balenos Forest", "A", 1, "Velia", "Ash Timber", "Spirit's Leaf")
	addProductionNode("Balenos Forest", "B", 1, "Velia", "Sunrise Herb", "Pile of Sunrise Herbs")
	addConnection("Balenos Forest", "Heidel Pass")
	addConnection("Balenos Forest", "Bartali Farm")
	addNode("Marino Farm", 2)
	addConnection("Marino Farm", "Bartali Farm")
	addNode("Toscani Farm", 2)
	addProductionNode("Toscani Farm", "A", 1, "Velia", "Corn")
	addProductionNode("Toscani Farm", "B", 1, "Velia", "Corn")
	addConnection("Toscani Farm", "Bartali Farm")
	addConnection("Toscani Farm", "Forest of Seclusion")
	addConnection("Toscani Farm", "Western Guard Camp")
	addNode("Imp Cave", 1)
	addProductionNode("Imp Cave", "A", 1, "Velia", "Copper Ore", "Powder of Flame")
	addProductionNode("Imp Cave", "B", 1, "Velia", "Copper Ore", "Powder of Flame")
	addConnection("Imp Cave", "Loggia Farm")
	addConnection("Imp Cave", "Western Guard Camp")
	addConnection("Imp Cave", "Altar of Agris")
	addNode("Altar of Agris", 1)
	addConnection("Altar of Agris", "Imp Cave")
	addNode("Coastal Cliff", 1)
	addProductionNode("Coastal Cliff", "A", 1, "Velia", "Fortune Teller Mushroom", "Big Fortune Teller Mushroom")
	addProductionNode("Coastal Cliff", "B", 1, "Velia", "Iron Ore", "Powder of Darkness")
	addConnection("Coastal Cliff", "Coastal Cave")
	addConnection("Coastal Cliff", "Western Gateway")
	addConnection("Coastal Cliff", "Balenos River Mouth")
	addNode("Western Guard Camp", 1)
	addConnection("Western Guard Camp", "Imp Cave")
	addConnection("Western Guard Camp", "Toscani Farm")
	addConnection("Western Guard Camp", "Bandit's Den Byway")
	addConnection("Western Guard Camp", "Western Gateway")
	addNode("Forest of Seclusion", 2)
	addProductionNode("Forest of Seclusion", "A", 1, "Velia", "Maple Timber", "Monk's Branch")
	addProductionNode("Forest of Seclusion", "B", 1, "Velia", "Copper Ore", "Powder of Flame")
	addConnection("Forest of Seclusion", "Toscani Farm")
	addConnection("Forest of Seclusion", "Ancient Stone Chamber")
	addConnection("Forest of Seclusion", "Bandit's Den Byway")
	addNode("Ancient Stone Chamber", 1)
	addProductionNode("Ancient Stone Chamber", "A", 1, "Velia", "Withered Leaf", "Cracked Fang", "Trace of the Earth", "Trace of Ascension")
	addConnection("Ancient Stone Chamber", "Forest of Seclusion")
	addNode("Bandit's Den Byway", 3)
	addConnection("Bandit's Den Byway", "Western Guard Camp")
	addConnection("Bandit's Den Byway", "Forest of Seclusion")
	addConnection("Bandit's Den Byway", "Biraghi Den")
	addNode("Cron Castle Site", 1)
	addProductionNode("Cron Castle Site", "A", 1, "Velia", "Sunrise Herb", "Pile of Sunrise Herbs")
	addConnection("Cron Castle Site", "Mediah Northern Gateway")
	addConnection("Cron Castle Site", "Ehwaz Hill")
	addConnection("Cron Castle Site", "Cron Castle")
	addNode("Mediah Northern Gateway", 3)
	addConnection("Mediah Northern Gateway", "The Mausoleum")
	addConnection("Mediah Northern Gateway", "Cron Castle Site")
	addNode("The Mausoleum", 1)
	addConnection("The Mausoleum", "Mediah Northern Highlands")
	addConnection("The Mausoleum", "Mediah Northern Gateway")
	addNode("Cron Castle", 2)
	addConnection("Cron Castle", "Cron Castle Site")
	addNode("Olvia", 0)
	addConnection("Olvia", "Casta Farm")
	addConnection("Olvia", "Wale Farm")
	addNode("Casta Farm", 1)
	addProductionNode("Casta Farm", "A", 1, "Olvia", "Grape")
	addConnection("Casta Farm", "Olvia Coast")
	addConnection("Casta Farm", "Wolf Hills")
	addConnection("Casta Farm", "Olvia")
	addNode("Olvia Coast", 1)
	addConnection("Olvia Coast", "Balenos River Mouth")
	addConnection("Olvia Coast", "Casta Farm")
	addNode("Balenos River Mouth", 1)
	addConnection("Balenos River Mouth", "Coastal Cliff")
	addConnection("Balenos River Mouth", "Wolf Hills")
	addConnection("Balenos River Mouth", "Olvia Coast")
	addNode("Wolf Hills", 1)
	addProductionNode("Wolf Hills", "A", 1, "Olvia", "Ash Timber")
	addConnection("Wolf Hills", "Balenos River Mouth")
	addConnection("Wolf Hills", "Western Gateway")
	addConnection("Wolf Hills", "Casta Farm")
	addNode("Western Gateway", 3)
	addConnection("Western Gateway", "Coastal Cliff")
	addConnection("Western Gateway", "Western Guard Camp")
	addConnection("Western Gateway", "Wolf Hills")
	addNode("Wale Farm", 1)
	addProductionNode("Wale Farm", "A", 1, "Olvia", "Olive")
	addConnection("Wale Farm", "Olvia")
	addConnection("Wale Farm", "Terrmian Cliff")
	addNode("Terrmian Cliff", 1)
	addProductionNode("Terrmian Cliff", "A", 1, "Olvia", "Copper Ore")
	addConnection("Terrmian Cliff", "Wale Farm")
	// TODO: addConnection("Terrmian Cliff", "Florin Gateway")
	addNode("Paratama Island", 1)
	addProductionNode("Paratama Island", "A", 1, "", "Dried Swellfish", "Dried Striped Catfish", "Dried Nibbler", "Dried Surfperch")
	// TODO: addConnection("Paratama Island", "Beiruwa Island")
	addConnection("Paratama Island", "Luivano Island")
	addConnection("Paratama Island", "Weita Island")
	addNode("Weita Island", 1)
	addProductionNode("Weita Island", "A", 1, "", "Dried Nibbler", "Dried Bluefish", "Dried Surfperch", "Dried Maomao")
	// TODO: addConnection("Weita Island", "Kanvera Island")
	addConnection("Weita Island", "Paratama Island")
	addConnection("Weita Island", "Baremi Island")
	addNode("Baremi Island", 1)
	// TODO: addConnection("Baremi Island", "Ajir Island")
	addConnection("Baremi Island", "Weita Island")
	addConnection("Baremi Island", "Orffs Island")
	addNode("Orffs Island", 1)
	addProductionNode("Orffs Island", "A", 1, "", "Dried Saurel", "Dried Grunt", "Dried Dolphinfish", "Dried Striped Catfish")
	addProductionNode("Orffs Island", "B", 1, "", "Dried Filefish", "Dried Grunt", "Dried Surfperch", "Dried Clownfish")
	addConnection("Orffs Island", "Lema Island")
	addConnection("Orffs Island", "Baremi Island")
	// TODO: addConnection("Orffs Island", "Tulu Island")
	addNode("Lema Island", 1)
	// TODO: addConnection("Lema Island", "Ross Sea 1405")
	addConnection("Lema Island", "Orffs Island")
	// TODO: addConnection("Lema Island", "Ross Sea 1400")
	// TODO: addConnection("Lema Island", "Ross Sea 1401")
	// TODO: addConnection("Lema Island", "Ross Sea 1402")
	// TODO: addConnection("Lema Island", "Ross Sea 1403")
	// TODO: addConnection("Lema Island", "Tashu Island")
	addConnection("Lema Island", "Port Ratt")
	// TODO: addConnection("Lema Island", "Ross Sea 1404")
	addNode("Port Ratt", 0)
	addConnection("Port Ratt", "Lema Island")
	// TODO: addConnection("Port Ratt", "Vadabin 1449")
	addConnection("Port Ratt", "Mariul Island")
	addNode("Mariul Island", 1)
	addConnection("Mariul Island", "Port Ratt")
	addConnection("Mariul Island", "Nada Island")
	addNode("Nada Island", 3)
	addProductionNode("Nada Island", "A", 2, "", "Oyster", "Dried Sea Bass", "Dried Swordfish", "Dried Flying Fish", "Dried Rosefish")
	addProductionNode("Nada Island", "B", 2, "", "Shrimp", "Dried Sea Bass", "Dried Swordfish", "Dried Flying Fish", "Dried Rosefish")
	addConnection("Nada Island", "Mariul Island")
	// TODO: addConnection("Nada Island", "Zagam Island")
	addNode("Heidel", 0)
	addConnection("Heidel", "Eastern Border")
	addConnection("Heidel", "Moretti Plantation")
	addConnection("Heidel", "Costa Farm")
	addConnection("Heidel", "Lynch Farm Ruins")
	addConnection("Heidel", "Northern Guard Camp")
	addNode("Eastern Border", 3)
	// TODO: addConnection("Eastern Border", "Rumbling Land")
	addConnection("Eastern Border", "Kamasylve Temple")
	addConnection("Eastern Border", "Heidel")
	addNode("Kamasylve Temple", 2)
	addProductionNode("Kamasylve Temple", "A", 2, "", "Tiger Mushroom", "Big Tiger Mushroom")
	addProductionNode("Kamasylve Temple", "B", 2, "", "Flax", "Flax Thread")
	addConnection("Kamasylve Temple", "Ancient Ruins Excavation Site")
	addConnection("Kamasylve Temple", "Ahto Farm")
	addConnection("Kamasylve Temple", "Castle Ruins")
	addConnection("Kamasylve Temple", "Eastern Border")
	addNode("Moretti Plantation", 2)
	addProductionNode("Moretti Plantation", "A", 1, "Heidel", "Wheat")
	addProductionNode("Moretti Plantation", "B", 1, "Heidel", "Flax", "Flax Thread")
	addConnection("Moretti Plantation", "Eastern Gateway")
	addConnection("Moretti Plantation", "Northern Cienaga")
	addConnection("Moretti Plantation", "Heidel")
	addNode("Costa Farm", 2)
	addProductionNode("Costa Farm", "A", 1, "Heidel", "Wheat")
	addProductionNode("Costa Farm", "B", 1, "Heidel", "Pumpkin")
	addProductionNode("Costa Farm", "C", 1, "Heidel", "Flax")
	addConnection("Costa Farm", "Heidel")
	addConnection("Costa Farm", "Central Guard Camp")
	addNode("Lynch Farm Ruins", 1)
	addProductionNode("Lynch Farm Ruins", "A", 1, "Heidel", "Silver Azalea", "Bunch of Silver Azaleas")
	addProductionNode("Lynch Farm Ruins", "B", 1, "Heidel", "Altar Imp's Broken Trumpet", "Wagon Wheel", "Cloth from the Altar Imp Barracks", "Trace of Savagery", "Trace of Hunting")
	addConnection("Lynch Farm Ruins", "Alejandro Farm")
	addConnection("Lynch Farm Ruins", "Heidel")
	addConnection("Lynch Farm Ruins", "Northwestern Gateway")
	addConnection("Lynch Farm Ruins", "Northern Plain of Serendia")
	addNode("Alejandro Farm", 2)
	addProductionNode("Alejandro Farm", "A", 1, "Heidel", "Pumpkin")
	addProductionNode("Alejandro Farm", "B", 1, "Heidel", "Cooking Honey")
	addConnection("Alejandro Farm", "Northern Guard Camp")
	addConnection("Alejandro Farm", "Lynch Farm Ruins")
	addNode("Northern Plain of Serendia", 1)
	addProductionNode("Northern Plain of Serendia", "A", 1, "", "Silver Azalea", "Bunch of Silver Azaleas")
	addProductionNode("Northern Plain of Serendia", "B", 1, "", "Maple Timber", "Red Tree Lump")
	addConnection("Northern Plain of Serendia", "Lynch Ranch")
	addConnection("Northern Plain of Serendia", "Lynch Farm Ruins")
	addConnection("Northern Plain of Serendia", "Bradie Fortress")
	addConnection("Northern Plain of Serendia", "Biraghi Den")
	addNode("Bradie Fortress", 1)
	addConnection("Bradie Fortress", "Northern Plain of Serendia")
	addConnection("Bradie Fortress", "Orc Camp")
	addConnection("Bradie Fortress", "Oze Pass")
	addNode("Orc Camp", 3)
	addConnection("Orc Camp", "Northwestern Gateway")
	addConnection("Orc Camp", "Watchtower")
	addConnection("Orc Camp", "Quarry Byway")
	addConnection("Orc Camp", "Bradie Fortress")
	addNode("Watchtower", 1)
	addConnection("Watchtower", "Southern Neutral Zone")
	addConnection("Watchtower", "Orc Camp")
	addNode("Lynch Ranch", 2)
	addProductionNode("Lynch Ranch", "A", 1, "Heidel", "Fleece", "Knitting Yarn")
	addConnection("Lynch Ranch", "Northern Plain of Serendia")
	addNode("Biraghi Den", 3)
	addConnection("Biraghi Den", "Bandit's Den Byway")
	addConnection("Biraghi Den", "Northern Plain of Serendia")
	addConnection("Biraghi Den", "Delphe Knights Castle")
	addNode("Northern Guard Camp", 3)
	addConnection("Northern Guard Camp", "Heidel Pass")
	addConnection("Northern Guard Camp", "Heidel")
	addConnection("Northern Guard Camp", "Alejandro Farm")
	// TODO: addConnection("Northern Guard Camp", "Northern Heidel Quarry")
	addNode("Glish", 0)
	addConnection("Glish", "Central Guard Camp")
	addConnection("Glish", "Southern Cienaga")
	addConnection("Glish", "Southwestern Gateway")
	addConnection("Glish", "Glish Swamp")
	addConnection("Glish", "Northwestern Gateway")
	addNode("Central Guard Camp", 3)
	addConnection("Central Guard Camp", "Northern Cienaga")
	addConnection("Central Guard Camp", "Glish Ruins")
	addConnection("Central Guard Camp", "Glish")
	addConnection("Central Guard Camp", "Costa Farm")
	addNode("Northern Cienaga", 2)
	addProductionNode("Northern Cienaga", "A", 1, "Heidel", "Dwarf Mushroom", "Big Dwarf Mushroom")
	addConnection("Northern Cienaga", "Moretti Plantation")
	addConnection("Northern Cienaga", "Eastern Gateway")
	addConnection("Northern Cienaga", "Central Guard Camp")
	addNode("Eastern Gateway", 3)
	addConnection("Eastern Gateway", "Moretti Plantation")
	addConnection("Eastern Gateway", "Castle Ruins")
	addConnection("Eastern Gateway", "Southern Guard Camp")
	addConnection("Eastern Gateway", "Northern Cienaga")
	addNode("Castle Ruins", 1)
	addProductionNode("Castle Ruins", "A", 1, "Heidel", "Maple Timber", "Maple Sap")
	addConnection("Castle Ruins", "Kamasylve Temple")
	// TODO: addConnection("Castle Ruins", "Soldier's Grave")
	addConnection("Castle Ruins", "Eastern Gateway")
	addNode("Glish Ruins", 1)
	addProductionNode("Glish Ruins", "A", 1, "Glish", "Black Dirt", "Sharp Helmet Fragment", "Dull Club Piece", "Trace of Origin", "Trace of Hunting")
	addConnection("Glish Ruins", "Southern Guard Camp")
	addConnection("Glish Ruins", "Central Guard Camp")
	addNode("Southern Guard Camp", 3)
	addConnection("Southern Guard Camp", "Eastern Gateway")
	addConnection("Southern Guard Camp", "Serendia Shrine")
	addConnection("Southern Guard Camp", "Southern Cienaga")
	addConnection("Southern Guard Camp", "Glish Ruins")
	addNode("Southern Cienaga", 1)
	addProductionNode("Southern Cienaga", "A", 1, "Glish", "Cloud Mushroom", "Big Cloud Mushroom")
	addProductionNode("Southern Cienaga", "B", 1, "Glish", "Iron Ore", "Rough Mud Crystal")
	addConnection("Southern Cienaga", "Southern Guard Camp")
	addConnection("Southern Cienaga", "Glish")
	addNode("Serendia Shrine", 1)
	addProductionNode("Serendia Shrine", "A", 1, "Glish", "Pine Timber", "Monk's Branch")
	addConnection("Serendia Shrine", "Southern Guard Camp")
	addNode("Southwestern Gateway", 3)
	addConnection("Southwestern Gateway", "Northwestern Gateway")
	addConnection("Southwestern Gateway", "Glish")
	addConnection("Southwestern Gateway", "Bloody Monastery")
	addConnection("Southwestern Gateway", "Southern Neutral Zone")
	addNode("Southern Neutral Zone", 3)
	addConnection("Southern Neutral Zone", "Watchtower")
	addConnection("Southern Neutral Zone", "Southwestern Gateway")
	addConnection("Southern Neutral Zone", "Closed Western Gateway")
	addConnection("Southern Neutral Zone", "Keplan Vicinity")
	addNode("Closed Western Gateway", 3)
	addConnection("Closed Western Gateway", "Southern Neutral Zone")
	addConnection("Closed Western Gateway", "Gianin Farm")
	addNode("Gianin Farm", 2)
	addConnection("Gianin Farm", "Closed Western Gateway")
	addConnection("Gianin Farm", "Gehaku Plain")
	addConnection("Gianin Farm", "Keplan Hill")
	addNode("Keplan Vicinity", 1)
	addConnection("Keplan Vicinity", "Southern Neutral Zone")
	addConnection("Keplan Vicinity", "Keplan")
	addConnection("Keplan Vicinity", "Quarry Byway")
	addNode("Glish Swamp", 1)
	addProductionNode("Glish Swamp", "A", 1, "Glish", "Cloud Mushroom", "Big Cloud Mushroom")
	addProductionNode("Glish Swamp", "B", 1, "Glish", "Lead Ore", "Powder of Time")
	addConnection("Glish Swamp", "Glish")
	addNode("Northwestern Gateway", 3)
	addConnection("Northwestern Gateway", "Lynch Farm Ruins")
	addConnection("Northwestern Gateway", "Glish")
	addConnection("Northwestern Gateway", "Southwestern Gateway")
	addConnection("Northwestern Gateway", "Orc Camp")
	addNode("Bloody Monastery", 1)
	addConnection("Bloody Monastery", "Southwestern Gateway")
	addNode("Port Epheria", 0)
	// TODO: addConnection("Port Epheria", "Epheria Ridge")
	addConnection("Port Epheria", "Epheria Sentry Post")
	// TODO: addConnection("Port Epheria", "Serca Island")
	addNode("Epheria Sentry Post", 3)
	addConnection("Epheria Sentry Post", "Port Epheria")
	addConnection("Epheria Sentry Post", "Epheria Valley")
	addNode("Epheria Valley", 1)
	addConnection("Epheria Valley", "Isolated Sentry Post")
	addConnection("Epheria Valley", "Epheria Sentry Post")
	addNode("Isolated Sentry Post", 3)
	// TODO: addConnection("Isolated Sentry Post", "Anti-Troll Fortification")
	// TODO: addConnection("Isolated Sentry Post", "Abandoned Land")
	// TODO: addConnection("Isolated Sentry Post", "Cohen Farm")
	addConnection("Isolated Sentry Post", "Epheria Valley")
	addConnection("Isolated Sentry Post", "Quint Hill")
	addNode("Quint Hill", 1)
	addProductionNode("Quint Hill", "A", 1, "Epheria Port", "Birch Timber", "Red Tree Lump")
	addProductionNode("Quint Hill", "B", 1, "Epheria Port", "Lead Ore", "Powder of Time")
	addConnection("Quint Hill", "Isolated Sentry Post")
	addNode("Calpheon", 0)
	// TODO: addConnection("Calpheon", "Contaminated Farm")
	addConnection("Calpheon", "Dias Farm")
	addConnection("Calpheon", "Falres Dirt Farm")
	addConnection("Calpheon", "Oberen Farm")
	addConnection("Calpheon", "Gabino Farm")
	// TODO: addConnection("Calpheon", "Abandoned Land")
	addNode("Oberen Farm", 2)
	addConnection("Oberen Farm", "Beacon Entrance Post")
	addConnection("Oberen Farm", "Bain Farmland")
	addConnection("Oberen Farm", "Calpheon")
	addNode("Beacon Entrance Post", 3)
	addConnection("Beacon Entrance Post", "Marni Cave Path")
	addConnection("Beacon Entrance Post", "Trina Beacon Mounds")
	addConnection("Beacon Entrance Post", "Oberen Farm")
	addNode("Trina Beacon Mounds", 3)
	addConnection("Trina Beacon Mounds", "Beacon Entrance Post")
	addConnection("Trina Beacon Mounds", "Trina Fort")
	addNode("Trina Fort", 3)
	addConnection("Trina Fort", "Tarte Rock Fork")
	addConnection("Trina Fort", "Saunil Battlefield")
	addConnection("Trina Fort", "Trina Beacon Mounds")
	addNode("Bain Farmland", 2)
	addConnection("Bain Farmland", "Oberen Farm")
	addConnection("Bain Farmland", "Phoniel's Cabin Entrance")
	addNode("Dias Farm", 2)
	addConnection("Dias Farm", "Delphe Knights Castle")
	addConnection("Dias Farm", "Falres Dirt Farm")
	addConnection("Dias Farm", "Calpheon")
	addConnection("Dias Farm", "Northern Wheat Plantation")
	addNode("Delphe Knights Castle", 3)
	addConnection("Delphe Knights Castle", "Delphe Outpost")
	addConnection("Delphe Knights Castle", "Biraghi Den")
	addConnection("Delphe Knights Castle", "Oze Pass")
	addConnection("Delphe Knights Castle", "Dias Farm")
	addNode("Falres Dirt Farm", 2)
	addConnection("Falres Dirt Farm", "Marni Farm Ruins")
	addConnection("Falres Dirt Farm", "Marni Cave Path")
	addConnection("Falres Dirt Farm", "Calpheon")
	addConnection("Falres Dirt Farm", "Dias Farm")
	addNode("Northern Wheat Plantation", 2)
	addProductionNode("Northern Wheat Plantation", "A", 1, "Calpheon", "Wheat")
	addProductionNode("Northern Wheat Plantation", "B", 1, "Calpheon", "Barley")
	addProductionNode("Northern Wheat Plantation", "C", 1, "Calpheon", "Paprika")
	addConnection("Northern Wheat Plantation", "Old Dandelion")
	addConnection("Northern Wheat Plantation", "Dias Farm")
	addConnection("Northern Wheat Plantation", "Berniato Farm")
	addNode("Old Dandelion", 1)
	addProductionNode("Old Dandelion", "A", 1, "Calpheon", "Birch Timber", "Red Tree Lump")
	addConnection("Old Dandelion", "Khuruto Cave")
	addConnection("Old Dandelion", "Delphe Outpost")
	addConnection("Old Dandelion", "Northern Wheat Plantation")
	addNode("Delphe Outpost", 3)
	addConnection("Delphe Outpost", "Karanda Ridge")
	addConnection("Delphe Outpost", "Delphe Knights Castle")
	addConnection("Delphe Outpost", "Old Dandelion")
	addNode("Karanda Ridge", 1)
	addProductionNode("Karanda Ridge", "A", 1, "", "Silk Honey Grass", "Bunch of Silk Honey Grass")
	addConnection("Karanda Ridge", "Delphe Outpost")
	addNode("Khuruto Cave", 1)
	addProductionNode("Khuruto Cave", "A", 1, "Calpheon", "Tin Ore", "Rough Red Crystal")
	addConnection("Khuruto Cave", "Old Dandelion")
	// TODO: addConnection("Khuruto Cave", "Florin")
	addNode("Berniato Farm", 2)
	addProductionNode("Berniato Farm", "A", 1, "Calpheon", "Contaminated Tooth", "Weathered Rock Fragment from Ruins Site", "Ancient Artifact Fragment", "Trace of Battle", "Trace of Forest")
	addConnection("Berniato Farm", "Bree Tree Ruins")
	addConnection("Berniato Farm", "Northern Wheat Plantation")
	// TODO: addConnection("Berniato Farm", "Anti-Troll Fortification")
	addNode("Bree Tree Ruins", 1)
	addProductionNode("Bree Tree Ruins", "A", 1, "Calpheon", "Birch Timber", "Birch Sap")
	addProductionNode("Bree Tree Ruins", "B", 1, "Calpheon", "Tiger Mushroom", "Big Tiger Mushroom")
	// TODO: addConnection("Bree Tree Ruins", "Caphras Cave")
	addConnection("Bree Tree Ruins", "Berniato Farm")
	addNode("Gabino Farm", 2)
	addConnection("Gabino Farm", "Calpheon")
	addConnection("Gabino Farm", "North Kaia Mountaintop")
	// TODO: addConnection("Gabino Farm", "North Kaia Ferry")
	addNode("North Kaia Mountaintop", 1)
	addConnection("North Kaia Mountaintop", "Phoniel's Cabin")
	addConnection("North Kaia Mountaintop", "Gabino Farm")
	addNode("Phoniel's Cabin", 2)
	addProductionNode("Phoniel's Cabin", "A", 1, "", "Fir Timber", "Fir Sap")
	addConnection("Phoniel's Cabin", "North Kaia Mountaintop")
	addConnection("Phoniel's Cabin", "Phoniel's Cabin Entrance")
	addConnection("Phoniel's Cabin", "Behr Riverhead")
	addConnection("Phoniel's Cabin", "Rhutum Sentry Post")
	addNode("Phoniel's Cabin Entrance", 1)
	addConnection("Phoniel's Cabin Entrance", "Bain Farmland")
	addConnection("Phoniel's Cabin Entrance", "Behr Downstream")
	addConnection("Phoniel's Cabin Entrance", "Phoniel's Cabin")
	addNode("Behr Riverhead", 1)
	addProductionNode("Behr Riverhead", "A", 1, "Calpheon", "Tin Ore", "Powder of Earth")
	addConnection("Behr Riverhead", "Behr Downstream")
	addConnection("Behr Riverhead", "Phoniel's Cabin")
	addNode("Behr Downstream", 3)
	addConnection("Behr Downstream", "Saunil Battlefield")
	addConnection("Behr Downstream", "Rhua Tree Stub")
	addConnection("Behr Downstream", "Behr")
	addConnection("Behr Downstream", "Behr Riverhead")
	addConnection("Behr Downstream", "Phoniel's Cabin Entrance")
	addNode("Saunil Battlefield", 1)
	addConnection("Saunil Battlefield", "Trina Fort")
	addConnection("Saunil Battlefield", "Saunil Camp")
	addConnection("Saunil Battlefield", "Rhua Tree Stub")
	addConnection("Saunil Battlefield", "Behr Downstream")
	addNode("Rhua Tree Stub", 1)
	addProductionNode("Rhua Tree Stub", "A", 1, "", "Emperor Mushroom", "Big Emperor Mushroom")
	addProductionNode("Rhua Tree Stub", "B", 1, "", "Dull Bone Fragment", "Weathered Cursed Fang", "Faded Magic Powder", "Trace of Despair", "Trace of Forest")
	addConnection("Rhua Tree Stub", "Saunil Battlefield")
	addConnection("Rhua Tree Stub", "Hexe Sanctuary")
	addConnection("Rhua Tree Stub", "Behr Downstream")
	addNode("Hexe Sanctuary", 2)
	addConnection("Hexe Sanctuary", "Witch's Chapel")
	addConnection("Hexe Sanctuary", "Rhua Tree Stub")
	addNode("Witch's Chapel", 1)
	addConnection("Witch's Chapel", "Marie Cave")
	addConnection("Witch's Chapel", "Hexe Sanctuary")
	addNode("Saunil Camp", 1)
	addConnection("Saunil Camp", "Dane Canyon")
	addConnection("Saunil Camp", "Saunil Battlefield")
	addNode("Dane Canyon", 2)
	addConnection("Dane Canyon", "Gehaku Plain")
	addConnection("Dane Canyon", "Saunil Camp")
	addNode("Behr", 1)
	addConnection("Behr", "Behr Downstream")
	addConnection("Behr", "Longleaf Tree Forest")
	addNode("Rhutum Sentry Post", 3)
	// TODO: addConnection("Rhutum Sentry Post", "South Kaia Ferry")
	addConnection("Rhutum Sentry Post", "Phoniel's Cabin")
	addConnection("Rhutum Sentry Post", "Rhutum Outstation")
	addNode("Rhutum Outstation", 1)
	addProductionNode("Rhutum Outstation", "A", 1, "Calpheon", "Tin Ore", "Rough Green Crystal")
	addConnection("Rhutum Outstation", "Rhutum Sentry Post")
	addConnection("Rhutum Outstation", "Tobare's Cabin")
	addNode("Tobare's Cabin", 2)
	addConnection("Tobare's Cabin", "Mansha Forest")
	addConnection("Tobare's Cabin", "Rhutum Outstation")
	addConnection("Tobare's Cabin", "Abandoned Monastery")
	addNode("Mansha Forest", 2)
	addProductionNode("Mansha Forest", "A", 1, "Trent", "Fir Timber", "Fir Sap")
	addProductionNode("Mansha Forest", "B", 1, "Trent", "Weathered Cursed Fang", "Tough Bear Hide", "Cursed Quartz Fragment", "Trace of Despair", "Trace of Violence")
	// TODO: addConnection("Mansha Forest", "Catfishman Camp")
	addConnection("Mansha Forest", "Tobare's Cabin")
	// TODO: addConnection("Mansha Forest", "Calpheon Castle Western Forest")
	addNode("Abandoned Monastery", 3)
	addConnection("Abandoned Monastery", "Lumberjack's Rest Area")
	// TODO: addConnection("Abandoned Monastery", "Treant Forest")
	addConnection("Abandoned Monastery", "Tobare's Cabin")
	addNode("Lumberjack's Rest Area", 1)
	addProductionNode("Lumberjack's Rest Area", "A", 1, "Trent", "Cedar Timber", "Spirit's Leaf")
	addConnection("Lumberjack's Rest Area", "Abandoned Monastery")
	addConnection("Lumberjack's Rest Area", "Trent")
	addNode("Trent", 0)
	addConnection("Trent", "Longleaf Tree Sentry Post")
	addConnection("Trent", "Lumberjack's Rest Area")
	addNode("Longleaf Tree Sentry Post", 2)
	addProductionNode("Longleaf Tree Sentry Post", "A", 1, "Trent", "Silk Honey Grass", "Bunch of Silk Honey Grass")
	addConnection("Longleaf Tree Sentry Post", "Crioville")
	addConnection("Longleaf Tree Sentry Post", "Trent")
	addNode("Crioville", 2)
	addConnection("Crioville", "Longleaf Tree Forest")
	addConnection("Crioville", "Longleaf Tree Sentry Post")
	addNode("Longleaf Tree Forest", 1)
	addProductionNode("Longleaf Tree Forest", "A", 1, "Trent", "Cedar Timber", "Cedar Sap")
	addConnection("Longleaf Tree Forest", "Behr")
	addConnection("Longleaf Tree Forest", "Crioville")
	addNode("Keplan", 0)
	addConnection("Keplan", "Keplan Quarry")
	addConnection("Keplan", "Keplan Vicinity")
	addConnection("Keplan", "Keplan Hill")
	addConnection("Keplan", "Tarte Rock Fork")
	addNode("Keplan Hill", 1)
	addConnection("Keplan Hill", "Gianin Farm")
	addConnection("Keplan Hill", "Keplan")
	addNode("Keplan Quarry", 1)
	addProductionNode("Keplan Quarry", "A", 1, "Keplan", "Coal", "Powder of Crevice")
	addConnection("Keplan Quarry", "Abandoned Quarry")
	addConnection("Keplan Quarry", "Keplan")
	addNode("Abandoned Quarry", 1)
	addConnection("Abandoned Quarry", "Oze's House")
	addConnection("Abandoned Quarry", "Keplan Quarry")
	addConnection("Abandoned Quarry", "Marni Cave Path")
	addNode("Marni Cave Path", 3)
	addConnection("Marni Cave Path", "Marni Farm Ruins")
	addConnection("Marni Cave Path", "Abandoned Quarry")
	addConnection("Marni Cave Path", "Marni's Lab")
	addConnection("Marni Cave Path", "Beacon Entrance Post")
	addConnection("Marni Cave Path", "Falres Dirt Farm")
	addNode("Marni's Lab", 1)
	addConnection("Marni's Lab", "Glutoni Cave")
	addConnection("Marni's Lab", "Marni Cave Path")
	addNode("Glutoni Cave", 1)
	addProductionNode("Glutoni Cave", "A", 1, "", "Emperor Mushroom", "Big Emperor Mushroom")
	addProductionNode("Glutoni Cave", "B", 1, "", "Coal", "Powder of Crevice")
	addConnection("Glutoni Cave", "Marni's Lab")
	addNode("Oze's House", 1)
	addConnection("Oze's House", "Oze Pass")
	addConnection("Oze's House", "Abandoned Quarry")
	addNode("Oze Pass", 1)
	addProductionNode("Oze Pass", "A", 1, "", "Cedar Timber", "Monk's Branch")
	addConnection("Oze Pass", "Delphe Knights Castle")
	addConnection("Oze Pass", "Bradie Fortress")
	addConnection("Oze Pass", "Quarry Byway")
	addConnection("Oze Pass", "Oze's House")
	addConnection("Oze Pass", "Marni Farm Ruins")
	addNode("Quarry Byway", 2)
	addConnection("Quarry Byway", "Orc Camp")
	addConnection("Quarry Byway", "Keplan Vicinity")
	addConnection("Quarry Byway", "Oze Pass")
	addNode("Marni Farm Ruins", 1)
	addConnection("Marni Farm Ruins", "Oze Pass")
	addConnection("Marni Farm Ruins", "Marni Cave Path")
	addConnection("Marni Farm Ruins", "Falres Dirt Farm")
	addNode("Tarte Rock Fork", 1)
	addConnection("Tarte Rock Fork", "Keplan")
	addConnection("Tarte Rock Fork", "Abandoned Quarry")
	addConnection("Tarte Rock Fork", "Trina Fort")
	addNode("Abandoned Quarry", 2)
	addConnection("Abandoned Quarry", "Gehaku Plain")
	addConnection("Abandoned Quarry", "Tarte Rock Fork")
	addNode("Gehaku Plain", 1)
	addConnection("Gehaku Plain", "Gianin Farm")
	addConnection("Gehaku Plain", "Primal Giant Post")
	addConnection("Gehaku Plain", "Dane Canyon")
	addConnection("Gehaku Plain", "Abandoned Quarry")
	addNode("Primal Giant Post", 1)
	addProductionNode("Primal Giant Post", "A", 1, "Keplan", "Lead Ore", "Powder of Crevice")
	addConnection("Primal Giant Post", "Gehaku Plain")
	addConnection("Primal Giant Post", "Hexe Stone Wall")
	addNode("Hexe Stone Wall", 1)
	addProductionNode("Hexe Stone Wall", "A", 1, "Keplan", "Iron Ore", "Powder of Darkness")
	addConnection("Hexe Stone Wall", "Primal Giant Post")
	addConnection("Hexe Stone Wall", "Marie Cave")
	addNode("Marie Cave", 1)
	addProductionNode("Marie Cave", "A", 1, "Keplan", "Pine Timber", "Pine Sap")
	addProductionNode("Marie Cave", "B", 1, "Keplan", "Ghost Mushroom", "Big Ghost Mushroom")
	addConnection("Marie Cave", "Hexe Stone Wall")
	addConnection("Marie Cave", "Witch's Chapel")
	addNode("Tarif", 0)
	addConnection("Tarif", "Kasula Farm")
	// TODO: addConnection("Tarif", "Soldier's Grave")
	addConnection("Tarif", "Manes Hideout")
	addNode("Kasula Farm", 2)
	addProductionNode("Kasula Farm", "A", 2, "Tarif", "Cotton", "Cotton Yarn")
	addProductionNode("Kasula Farm", "B", 2, "Tarif", "Cinnamon")
	addConnection("Kasula Farm", "Asula Highland")
	// TODO: addConnection("Kasula Farm", "Wandering Rogue Den")
	addConnection("Kasula Farm", "Tarif")
	addNode("Asula Highland", 1)
	addConnection("Asula Highland", "Omar Lava Cave")
	// TODO: addConnection("Asula Highland", "Highland Junction")
	addConnection("Asula Highland", "Kasula Farm")
	// TODO: addConnection("Asula Highland", "Stonetail Horse Ranch")
	addNode("Omar Lava Cave", 2)
	addProductionNode("Omar Lava Cave", "A", 3, "Tarif", "Zinc Ore", "Powder of Time", "Platinum Ore")
	addProductionNode("Omar Lava Cave", "B", 3, "Tarif", "Coal", "Powder of Crevice", "Rough Ruby")
	// TODO: addConnection("Omar Lava Cave", "Stonebeak Shore")
	// TODO: addConnection("Omar Lava Cave", "Awakening Bell")
	addConnection("Omar Lava Cave", "Asula Highland")
	// TODO: addConnection("Omar Lava Cave", "Mediah Shore")
	addNode("Manes Hideout", 1)
	addConnection("Manes Hideout", "Ahto Farm")
	addConnection("Manes Hideout", "Tarif")
	addNode("Ahto Farm", 2)
	addProductionNode("Ahto Farm", "A", 2, "Tarif", "Cotton", "Cotton Yarn")
	addProductionNode("Ahto Farm", "B", 2, "Tarif", "Aloe")
	// TODO: addConnection("Ahto Farm", "Stonetail Horse Ranch")
	addConnection("Ahto Farm", "Manes Hideout")
	addConnection("Ahto Farm", "Kamasylve Temple")
	addNode("Ancient Ruins Excavation Site", 1)
	addProductionNode("Ancient Ruins Excavation Site", "A", 3, "Tarif", "Obscuring Golem Fragment", "Helmet Ornament", "Trace of the Earth", "Trace of Chaos")
	addConnection("Ancient Ruins Excavation Site", "Canyon of Corruption")
	addConnection("Ancient Ruins Excavation Site", "Kamasylve Temple")
	// TODO: addConnection("Ancient Ruins Excavation Site", "Ancient Fissure")
	addNode("Canyon of Corruption", 1)
	addConnection("Canyon of Corruption", "Stonetail Wasteland")
	addConnection("Canyon of Corruption", "Shuri Farm")
	addConnection("Canyon of Corruption", "Ancient Ruins Excavation Site")
	addConnection("Canyon of Corruption", "Elric Shrine")
	addNode("Stonetail Wasteland", 1)
	addProductionNode("Stonetail Wasteland", "A", 3, "Tarif", "Acacia Timber", "Acacia Sap", "Bloody Tree Knot")
	// TODO: addConnection("Stonetail Wasteland", "Sausan Garrison")
	// TODO: addConnection("Stonetail Wasteland", "Kusha")
	addConnection("Stonetail Wasteland", "Canyon of Corruption")
	addNode("Shuri Farm", 2)
	addProductionNode("Shuri Farm", "A", 2, "Tarif", "Sweet Potato", "High-Quality Sweet Potato", "Special Sweet Potato")
	// TODO: addConnection("Shuri Farm", "Mediah Shore")
	// TODO: addConnection("Shuri Farm", "Stonetail Horse Ranch")
	addConnection("Shuri Farm", "Canyon of Corruption")
	addNode("Elric Shrine", 1)
	addProductionNode("Elric Shrine", "A", 3, "Tarif", "Sky Mushroom", "Big Sky Mushroom")
	addProductionNode("Elric Shrine", "B", 3, "Tarif", "White Cedar Timber", "White Cedar Sap", "Bloody Tree Knot")
	addConnection("Elric Shrine", "Canyon of Corruption")
	addConnection("Elric Shrine", "Mediah Northern Highlands")
	addNode("Mediah Northern Highlands", 2)
	addProductionNode("Mediah Northern Highlands", "A", 3, "Tarif", "White Cedar Timber", "White Cedar Sap", "Old Tree Bark")
	addProductionNode("Mediah Northern Highlands", "B", 3, "Tarif", "Maple Timber", "Maple Sap", "Old Tree Bark")
	// TODO: addConnection("Mediah Northern Highlands", "Sausan Garrison")
	addConnection("Mediah Northern Highlands", "Elric Shrine")
	// TODO: addConnection("Mediah Northern Highlands", "Helms Post")
	addConnection("Mediah Northern Highlands", "The Mausoleum")
	addNode("Altinova", 0)
	addConnection("Altinova", "Altinova Gateway")
	// TODO: addConnection("Altinova", "Abun")
	addConnection("Altinova", "Altinova Entrance")
	addNode("Altinova Entrance", 1)
	addConnection("Altinova Entrance", "Altinova")
	addConnection("Altinova Entrance", "Abandoned Iron Mine")
	// TODO: addConnection("Altinova Entrance", "Highland Junction")
	// TODO: addConnection("Altinova Entrance", "Awakening Bell")
	// TODO: addConnection("Altinova Entrance", "Stonebeak Shore")
	addNode("Abandoned Iron Mine", 2)
	addProductionNode("Abandoned Iron Mine", "A", 3, "Altinova", "Zinc Ore", "Powder of Time", "Platinum Ore")
	addProductionNode("Abandoned Iron Mine", "B", 3, "Altinova", "Iron Ore", "Powder of Darkness", "Rough Black Crystal")
	addConnection("Abandoned Iron Mine", "Altinova Entrance")
	// TODO: addConnection("Abandoned Iron Mine", "Abandoned Iron Mine Rhutum District")
	// TODO: addConnection("Abandoned Iron Mine", "Abandoned Iron Mine Saunil District")
	addNode("Altinova Gateway", 3)
	addConnection("Altinova Gateway", "Rock Post")
	addConnection("Altinova Gateway", "Altinova")
	addNode("Rock Post", 3)
	addConnection("Rock Post", "Altinova Gateway")
	// TODO: addConnection("Rock Post", "Gorgo Rock Belt")
	addConnection("Rock Post", "Veteran's Canyon")
	addNode("Veteran's Canyon", 1)
	addProductionNode("Veteran's Canyon", "A", 3, "Altinova", "Elder Tree Timber", "Elder Tree Plank", "Elder Tree Sap")
	addConnection("Veteran's Canyon", "Cadry Ruins")
	// TODO: addConnection("Veteran's Canyon", "Taphtar Plain")
	addConnection("Veteran's Canyon", "Rock Post")
	addNode("Cadry Ruins", 1)
	// TODO: addConnection("Cadry Ruins", "Ruined City of Rune")
	addConnection("Cadry Ruins", "Veteran's Canyon")
	addConnection("Cadry Ruins", "Kunid's Vacation Spot")
	addNode("Kunid's Vacation Spot", 1)
	addProductionNode("Kunid's Vacation Spot", "A", 3, "Altinova", "Bag of Muddy Water", "Purified Water")
	addConnection("Kunid's Vacation Spot", "Cadry Ruins")
	addNode("Shakatu", 0)
	addConnection("Shakatu", "Yalt Canyon")
	// TODO: addConnection("Shakatu", "Rune Gateway Intersection")
	// TODO: addConnection("Shakatu", "Abandoned Ferry in Shakatu")
	// TODO: addConnection("Shakatu", "Hope Ferry")
	// TODO: addConnection("Shakatu", "Shakatu Farmland")
	addNode("Yalt Canyon", 1)
	addConnection("Yalt Canyon", "Gahaz Bandit's Lair")
	addConnection("Yalt Canyon", "Shakatu")
	addNode("Gahaz Bandit's Lair", 1)
	addConnection("Gahaz Bandit's Lair", "Bambu Valley")
	addConnection("Gahaz Bandit's Lair", "Yalt Canyon")
	addNode("Bambu Valley", 1)
	addProductionNode("Bambu Valley", "A", 3, "Shakatu", "Freekah")
	addConnection("Bambu Valley", "Iris Canyon")
	addConnection("Bambu Valley", "Gahaz Bandit's Lair")
	addNode("Iris Canyon", 1)
	addProductionNode("Iris Canyon", "A", 3, "Shakatu", "Nutmeg")
	addProductionNode("Iris Canyon", "A", 3, "Shakatu", "Elder Tree Timber", "Elder Tree Plank", "Elder Tree Sap")
	addConnection("Iris Canyon", "Kmach Canyon")
	addConnection("Iris Canyon", "Bambu Valley")
	addNode("Kmach Canyon", 1)
	addProductionNode("Kmach Canyon", "A", 3, "Shakatu", "Vanadium Ore", "Powder of Crevice", "Rough Blue Crystal")
	addProductionNode("Kmach Canyon", "B", 3, "Shakatu", "Star Anise")
	// TODO: addConnection("Kmach Canyon", "Ancado Coast")
	addConnection("Kmach Canyon", "Iris Canyon")
	addNode("Sand Grain Bazaar", 0)
	// TODO: addConnection("Sand Grain Bazaar", "Pilgrim's Haven")
	addConnection("Sand Grain Bazaar", "Bazaar Farmland")
	addConnection("Sand Grain Bazaar", "Capotia")
	// TODO: addConnection("Sand Grain Bazaar", "Desert Naga Temple")
	addNode("Capotia", 1)
	addProductionNode("Capotia", "A", 3, "Sand Grain Bazaar", "Teff")
	addProductionNode("Capotia", "B", 3, "Sand Grain Bazaar", "Copper Ore", "Powder of Flame", "Rough Opal")
	addConnection("Capotia", "Sand Grain Bazaar")
	// TODO: addConnection("Capotia", "Barhan Gateway")
	addNode("Bazaar Farmland", 2)
	addProductionNode("Bazaar Farmland", "A", 3, "Sand Grain Bazaar", "Nutmeg")
	addProductionNode("Bazaar Farmland", "B", 3, "Sand Grain Bazaar", "Teff")
	addConnection("Bazaar Farmland", "Sand Grain Bazaar")
	addConnection("Bazaar Farmland", "Western Plateau of Valencia")
	addNode("Western Plateau of Valencia", 1)
	addConnection("Western Plateau of Valencia", "Crescent Mountains")
	addConnection("Western Plateau of Valencia", "Bazaar Farmland")
	addNode("Crescent Mountains", 3)
	addProductionNode("Crescent Mountains", "A", 3, "Sand Grain Bazaar", "Iron Ore", "Powder of Darkness", "Rough Black Crystal")
	addProductionNode("Crescent Mountains", "B", 3, "Sand Grain Bazaar", "Iron Ore", "Powder of Darkness", "Rough Black Crystal")
	addConnection("Crescent Mountains", "Akman")
	addConnection("Crescent Mountains", "Crescent Shrine")
	addConnection("Crescent Mountains", "Western Plateau of Valencia")
	addNode("Crescent Shrine", 1)
	addProductionNode("Crescent Shrine", "A", 3, "Sand Grain Bazaar", "Date Palm")
	addProductionNode("Crescent Shrine", "B", 3, "Sand Grain Bazaar", "Titanium Ore", "Powder of Flame", "Rough Violet Crystal")
	addConnection("Crescent Shrine", "Crescent Mountains")
	addNode("Akman", 5)
	addProductionNode("Akman", "A", 3, "Sand Grain Bazaar", "Fig")
	// TODO: addConnection("Akman", "Pilgrim's Sanctum: Sincerity")
	addConnection("Akman", "Pilgrim's Sanctum: Humility")
	addConnection("Akman", "Crescent Mountains")
	addNode("Pilgrim's Sanctum: Humility", 3)
	addProductionNode("Pilgrim's Sanctum: Humility", "A", 1, "Valencia City", "Desert Fogan's Helmet Shard", "Token of Crescent", "Ancient Civilization Follower's Seal", "Trace of Memory")
	// TODO: addConnection("Pilgrim's Sanctum: Humility", "Pilgrim's Sanctum: Purity")
	addConnection("Pilgrim's Sanctum: Humility", "Titium Valley")
	addConnection("Pilgrim's Sanctum: Humility", "Akman")
	// TODO: addConnection("Pilgrim's Sanctum: Humility", "Pilgrim's Sanctum: Sincerity")
	addNode("Titium Valley", 3)
	addProductionNode("Titium Valley", "A", 3, "Valencia City", "Pistachio")
	addProductionNode("Titium Valley", "B", 3, "Valencia City", "Teff")
	addProductionNode("Titium Valley", "C", 3, "Valencia City", "Palm Timber", "Palm Plank", "Palm Sap")
	addConnection("Titium Valley", "Muiquun")
	addConnection("Titium Valley", "Pilgrim's Sanctum: Humility")
	// TODO: addConnection("Titium Valley", "Pilgrim's Sanctum: Purity")
	addNode("Muiquun", 0)
	addConnection("Muiquun", "Cantusa Desert")
	addConnection("Muiquun", "Titium Valley")
	addNode("Cantusa Desert", 2)
	// TODO: addConnection("Cantusa Desert", "Pila Ku Jail")
	// TODO: addConnection("Cantusa Desert", "Dona Rocky Mountain")
	addConnection("Cantusa Desert", "Central Cantusa")
	addConnection("Cantusa Desert", "Muiquun")
	addNode("Central Cantusa", 1)
	addConnection("Central Cantusa", "Arehaza Town")
	addConnection("Central Cantusa", "Cantusa Desert")
	addNode("Arehaza Town", 0)
	// TODO: addConnection("Arehaza Town", "Northern Sand Dune")
	addConnection("Arehaza Town", "Central Cantusa")
	addConnection("Arehaza Town", "Areha Palm Forest")
	addNode("Areha Palm Forest", 1)
	addProductionNode("Areha Palm Forest", "A", 3, "Arehaza Town", "Palm Timber", "Palm Plank", "Coconut")
	addProductionNode("Areha Palm Forest", "B", 3, "Arehaza Town", "Palm Timber", "Palm Plank", "Coconut")
	addConnection("Areha Palm Forest", "Arehaza Town")
	addConnection("Areha Palm Forest", "Valencia City")
	addNode("Valencia City", 0)
	// TODO: addConnection("Valencia City", "Valencia Castle Site")
	addConnection("Valencia City", "Areha Palm Forest")
	addConnection("Valencia City", "Valencia Plantation")
	// TODO: addConnection("Valencia City", "Rakshan Observatory")
	addNode("Valencia Plantation", 2)
	addProductionNode("Valencia Plantation", "A", 3, "Valencia City", "Pistachio")
	addProductionNode("Valencia Plantation", "B", 3, "Valencia City", "Date Palm")
	addProductionNode("Valencia Plantation", "C", 3, "Valencia City", "Freekah")
	addConnection("Valencia Plantation", "Erdal Farm")
	addConnection("Valencia Plantation", "Valencia City")
	// TODO: addConnection("Valencia Plantation", "Fohalam Farm")
	addNode("Erdal Farm", 2)
	addProductionNode("Erdal Farm", "A", 3, "Valencia City", "Pistachio")
	addProductionNode("Erdal Farm", "B", 3, "Valencia City", "Date Palm")
	addProductionNode("Erdal Farm", "C", 3, "Valencia City", "Silkworm Cocoon", "Silk Thread")
	addConnection("Erdal Farm", "Valencia Plantation")
	for name, _ := range nodes {
		for nameB := range connections[name] {
			if _, ok := nodes[nameB]; !ok {
				panic(fmt.Sprintf("%s -> %s", name, nameB))
			}
			if _, ok := connections[nameB][name]; !ok {
				panic(fmt.Sprintf("%s <- %s", name, nameB))
			}
		}
	}
}
